package moe.ouom.neriplayer.core.player.usb.transport

data class UsbExclusiveNativeState(
    val available: Boolean = false,
    val opened: Boolean = false,
    val streaming: Boolean = false,
    val paused: Boolean = false,
    val transitioning: Boolean = false,
    val source: String = "idle",
    val handle: Long = 0L,
    val selectedDeviceName: String? = null,
    val inputFormat: String = "none",
    val outputFormat: String = "none",
    val requestedOutputFormat: String = "none",
    val outputSampleRate: Int = 0,
    val bufferDurationMs: Int = 250,
    val completedAudioFrames: Long = 0L,
    val queuedAudioFrames: Long = 0L,
    val pcmLevelBytes: Long = 0L,
    val pcmCapacityBytes: Long = 0L,
    val pcmFreeBytes: Long = 0L,
    val pcmBackpressureEvents: Long = 0L,
    val pcmBackpressureTotalMs: Long = 0L,
    val pcmBackpressureCurrentMs: Long = 0L,
    val pcmBackpressureMaxMs: Long = 0L,
    val playerSignalFrames: Long = 0L,
    val playerSilentFrames: Long = 0L,
    val playerSignalBytes: Long = 0L,
    val playerDroppedBytes: Long = 0L,
    val playerUnderrunBytes: Long = 0L,
    val playerZeroFillBytes: Long = 0L,
    val playerPausedZeroFillBytes: Long = 0L,
    val outputPeak: Float = 0f,
    val lastOutputPeak: Float = 0f,
    val runtimeReport: String = "idle",
    val lastError: String? = null
)
